### ISSUE TITLE
Incompatible with active_admin

### ISSUE THREAD

**Issue by robotmay** [copycopter/copycopter-ruby-client#29]
Currently experiencing the following error with every version of active_admin from 0.4.0 to current master (this exception taken while using master):

```
/Users/robertmay/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/inflector/methods.rb:97:in `block in humanize': undefined method `downcase' for nil:NilClass (NoMethodError)
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/core_ext/string/output_safety.rb:160:in `gsub'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/core_ext/string/output_safety.rb:160:in `gsub'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/inflector/methods.rb:97:in `humanize'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/inflector/methods.rb:112:in `titleize'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/core_ext/string/inflections.rb:95:in `titleize'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/resource/naming.rb:23:in `resource_label'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/resource/naming.rb:32:in `plural_resource_label'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/batch_actions/resource_extension.rb:52:in `add_default_batch_actions'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/batch_actions/resource_extension.rb:9:in `initialize'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/namespace.rb:130:in `new'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/namespace.rb:130:in `find_or_build_resource'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/namespace.rb:50:in `register'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin/application.rb:100:in `register'
    from /Users/robertmay/.rvm/gems/ruby-1.9.3-p125/bundler/gems/active_admin-c183c89f1c69/lib/active_admin.rb:74:in `register'
    from /Users/robertmay/Development/Rails/BPB/app/admin/articles.rb:1:in `<top (required)>'
```

**Comment by ChasManRors** [comment]
I am using CopyCopter with ActiveAdmin.  I get the following Timeout Errors in the messages and the Admin side moves like molasses.  Why is copycopter even being messaged from the ActiveAdmin views?

14 matches for "Copycopter" in buffer: _run_
     12:*\* [Copycopter] [P:12387] [T:70108530607720] Timeout::Error: Timeout::Error
     16:*\* [Copycopter] [P:12387] [T:70108512996560] Downloaded translations
     22:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: Timeout::Error
     38:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: execution expired
     43:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: Timeout::Error
     55:*\* [Copycopter] [P:12387] [T:70108512996560] Downloaded translations
     60:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: Timeout::Error
     72:*\* [Copycopter] [P:12387] [T:70108512996560] Downloaded translations
     79:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: execution expired
    191:*\* [Copycopter] [P:12387] [T:70108512996560] No new translations
    196:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: Timeout::Error
    204:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: execution expired
    244:*\* [Copycopter] [P:12387] [T:70108512996560] Downloaded translations
    249:*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: Timeout::Error

A little more context for some messages above:

Started GET "/assets/active_admin/nested_menu_arrow_dark.gif" for 127.0.0.1 at 2012-07-31 10:36:34 -0400
Served asset /active_admin/nested_menu_arrow_dark.gif - 200 OK (7ms)

Started GET "/admin/my_page" for 127.0.0.1 at 2012-07-31 10:36:50 -0400
*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: execution expired
Processing by Admin::MyPageController#index as HTML
  AdminUser Load (0.3ms)  SELECT "admin_users".\* FROM "admin_users" WHERE "admin_users"."id" = 1 LIMIT 1
  Rendered /Users/cmmagid/.rvm/gems/ruby-1.9.3-p125@rails32/gems/activeadmin-0.4.4/app/views/active_admin/page/index.html.arb (40.4ms)
Completed 200 OK in 48ms (Views: 43.1ms | ActiveRecord: 0.3ms)
*\* [Copycopter] [P:12387] [T:70108512996560] Timeout::Error: Timeout::Error

Started GET "/assets/active_admin.css?body=1" for 127.0.0.1 at 2012-07-31 10:37:01 -0400
Served asset /active_admin.css - 304 Not Modified (4ms)

**Comment by jubari** [comment]
Having similar problems... ActiveAdmin pages take 3-5 seconds to load

Started GET "/admin/orders" for 127.0.0.1 at 2012-08-06 18:15:43 +0200
*\* [Copycopter] [P:35819] [T:2151894860] Downloaded translations
Processing by Admin::OrdersController#index as HTML
[....]
*\* [Copycopter] [P:35819] [T:2151894860] Timeout::Error: Timeout::Error

**Comment by leklund** [comment]
The "undefined method `downcase' for nil:NilClass (NoMethodError)" error was caused by a bug in active_support: https://github.com/rails/rails/issues/4703

I believe the timeout errors are a separate issue.
