### ISSUE TITLE
copycopter-client and copycopter-server running on heroku - Is this supported?

### ISSUE THREAD

**Issue by railyboy** [copycopter/copycopter-ruby-client#30]
I've followed Ryan Bates screencast on setting up copycopter and have deployed both the server and client application utilising Copycopter to heroku.

I can run copycopter locally, but when I then push the git repo to Heroku which includes Copycopter client I get the service crashing.

I have an included .rvmrc file, and do not have enough experience with Heroku to know whether to include this and if it may be contributing to my problem.

I'm running on ruby-1.9.2-p290 with Rails 3.2.3 and the latest version of Copycopter (2.0.1).

The error message I receive when view the log files is as follows:

``` ruby
Vigor16:GDemo railsdev$ heroku ps
Process  State           Command                            
web.1    crashed for 1s  bundle exec rails server -p $PORT  
```

``` ruby
Vigor16:GDemo railsdev$ heroku logs
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/config.ru:1:in `new'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `parse_file'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:50:in `tap'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:252:in `start'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/server.rb:46:in `app'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:55:in `block in <top (required)>'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/server.rb:70:in `start'
2012-04-17T13:10:55+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:50:in `<top (required)>'
2012-04-17T13:10:55+00:00 app[web.1]:   from script/rails:6:in `<main>'
2012-04-17T13:10:55+00:00 app[web.1]:   from script/rails:6:in `require'
2012-04-17T13:10:56+00:00 heroku[web.1]: Process exited with status 1
2012-04-17T13:10:56+00:00 heroku[web.1]: State changed from starting to crashed
2012-04-17T13:10:56+00:00 heroku[web.1]: State changed from crashed to created
2012-04-17T13:10:56+00:00 heroku[web.1]: State changed from created to starting
2012-04-17T13:11:02+00:00 heroku[web.1]: Starting process with command `bundle exec rails server -p 5208`
2012-04-17T13:11:05+00:00 app[web.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-17T13:11:05+00:00 app[web.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-17T13:11:05+00:00 app[web.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-17T13:11:08+00:00 app[web.1]: => Rails 3.2.3 application starting in production on http://0.0.0.0:5208
2012-04-17T13:11:08+00:00 app[web.1]: => Booting WEBrick
2012-04-17T13:11:08+00:00 app[web.1]: => Call with -d to detach
2012-04-17T13:11:08+00:00 app[web.1]: => Ctrl-C to shutdown server
2012-04-17T13:11:08+00:00 app[web.1]: /app/config/initializers/copycopter.rb:1:in `<top (required)>': uninitialized constant CopycopterClient (NameError)
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
2012-04-17T13:11:08+00:00 app[web.1]: Exiting
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/engine.rb:587:in `each'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `instance_exec'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/engine.rb:587:in `block in <class:Engine>'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `run'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `each'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/application.rb:136:in `initialize!'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `run_initializers'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/config/environment.rb:5:in `<top (required)>'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/config.ru:4:in `require'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/config.ru:4:in `block in <main>'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/config.ru:1:in `new'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/config.ru:1:in `<main>'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `parse_file'
2012-04-17T13:11:08+
00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/server.rb:46:in `app'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:252:in `start'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/server.rb:70:in `start'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:55:in `block in <top (required)>'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:50:in `tap'
2012-04-17T13:11:08+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:50:in `<top (required)>'
2012-04-17T13:11:08+00:00 app[web.1]:   from script/rails:6:in `require'
2012-04-17T13:11:08+00:00 app[web.1]:   from script/rails:6:in `<main>'
2012-04-17T13:11:09+00:00 heroku[web.1]: Process exited with status 1
2012-04-17T13:11:09+00:00 heroku[web.1]: State changed from starting to crashed
2012-04-17T13:21:16+00:00 heroku[web.1]: State changed from crashed to created
2012-04-17T13:21:17+00:00 heroku[web.1]: State changed from created to starting
2012-04-17T13:21:23+00:00 heroku[web.1]: Starting process with command `bundle exec rails server -p 41445`
2012-04-17T13:21:29+00:00 app[web.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-17T13:21:29+00:00 app[web.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-17T13:21:29+00:00 app[web.1]: DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /app/config/environment.rb:5)
2012-04-17T13:21:33+00:00 app[web.1]: => Booting WEBrick
2012-04-17T13:21:33+00:00 app[web.1]: => Rails 3.2.3 application starting in production on http://0.0.0.0:41445
2012-04-17T13:21:33+00:00 app[web.1]: => Ctrl-C to shutdown server
2012-04-17T13:21:33+00:00 app[web.1]: => Call with -d to detach
2012-04-17T13:21:33+00:00 app[web.1]: Exiting
2012-04-17T13:21:33+00:00 app[web.1]: /app/config/initializers/copycopter.rb:1:in `<top (required)>': uninitialized constant CopycopterClient (NameError)
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/engine.rb:587:in `each'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/engine.rb:587:in `block in <class:Engine>'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `instance_exec'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `run'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `each'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `run_initializers'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/application.rb:136:in `initialize!'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/config.ru:4:in `require'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/config.ru:4:in `block in <main>'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/config/environment.rb:5:in `<top (required)>'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/config.ru:1:in `<main>'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/config.ru:1:in `new'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:252:in `start'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `parse_file'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/server.rb:46:in `app'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/server.rb:70:in `start'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:55:in `block in <top (required)>'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:50:in `tap'
2012-04-17T13:21:33+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:50:in `<top (required)>'
2012-04-17T13:21:33+00:00 app[web.1]:   from script/rails:6:in `require'
2012-04-17T13:21:33+00:00 app[web.1]:   from script/rails:6:in `<main>'
2012-04-17T13:21:34+00:00 heroku[web.1]: Process exited with status 1
2012-04-17T13:21:34+00:00 heroku[web.1]: State changed from starting to crashed
Vigor16:GDemo railsdev$ 
```

I have no ideas as to whether both services can be run from heroku. I have an OSS project that I am about to collaborate on where all the team are remote, so I thought this would be a great tool to allow our business users to review the copy and provide feedback.

Maybe I have misunderstood something.

I do notice the DEPRECATION warning but don't know where this originates. As the only difference between when I first deployed the app and now is the additiona of the copycopter.rb file in config/initializers I assume its related to copycopter.

**Comment by patricksrobertson** [comment]
Thanks for opening an issue.

I've created a brand, spanking new Rails 3.2.3 application, initialized a new OSS version of copycopter-server, and thrown up a blurb in a key.

The repo that utilizes the client gem is here:
https://github.com/patricksrobertson/copycopter-client-app

The resulting heroku deployment is located here:
http://copycopter-client-example.herokuapp.com/

I used a fresh clone/install/deployment of the copycopter-server and the result is here:
http://copycopter-example-server.herokuapp.com/
I have a project called 'example'.  The username is admin and the password is password

I was able to successfully deploy both applications on Heroku's Cedar stack (as far as I know that's the only stack that supports Rails 3.2+ with Ruby 1.9.2+) and the largest issue I ran into was overriding Rails' default of sqlite3 in favor of Heroku's default of PG.  

If I can help any further I'd love to.
